### ISSUE TITLE
Output argument should be directory

### ISSUE THREAD

**Issue by schackartk** [vanessajurtz/MetaPhinder#1]
Hello!

In your README.md you specify:

`-o output file (text file)`

 and in your example usage, you are including `-o output.txt`

However, in your actual code, you are treating the `-o` argument as a directory. Running your example usage with a text file for `-o` gives an error:

`Command line argument error: Argument "out". File is not accessible:  'example_output.txt/blast.out'  `

This is also consistent with your argument parsing

`parser.add_option('-o','--outpath', dest="outpath", help="path to output file(s)")`

**Comment by schackartk** [comment]
Additionally, there is a typo in your example command, where MetaPhinder is missing an "h":

`python MetaPinder.py -i infile.fsa -o output.txt -d database -b path_to_blast`

 This is a small thing, but can be troublesome when copy/pasting.

**Comment by vanessajurtz** [comment]
Hi Kenneth,

thank you very much for pointing this out! I've changed the readme file to make this clear.

Best wishes,
Vanessa

**Comment by schackartk** [comment]
Awesome! Thank you for your continued support.
