### ISSUE TITLE
BLAST Database error and NameError in MetaPhinder.py

### ISSUE THREAD

**Issue by schackartk** [vanessajurtz/MetaPhinder#2]
Thanks for your continued support of this tool!

I am getting the following error when running MetaPhinder on a FASTA file of contig-like sequences:

```
$  python MetaPhinder.py -i in.fa -d database
parsing commandline options...
running BLAST...
BLAST Database error: No alias or index file found for nucleotide database [database] in search path [/path/to/metaphinder_reprex::]
calculating ANI...
Traceback (most recent call last):
  File "MetaPhinder.py", line 228, in <module>
    if (old_id != str(l[0])) and (old_id != ""):
NameError: name 'l' is not defined
```

I have provided the files to reproduce this error on [Figshare](https://figshare.com/articles/dataset/MetaPhinder_Error_Reprex/16435329), including the FASTA file I am using, and a conda environment YAML file.

The command is being run in the directory where this repo is cloned, and where `MetaPhinder.py`, `in.fa`, and `database/` are located.

Including the BLAST location gives the same output as above:
`$ python MetaPhinder.py -i in.fa -d database -b  ~/.conda/envs/metaphinder_env/bin/`

I think there are two problems here: 

1. Some files may be missing from the database provided in this repo so that BLAST isn't able to run properly. This is likely causing the error shown in the above output. After running,  `blast.out` is created but is empty.
2. The `MetaPhinder.py` code on lines 228-237 is duplicated from lines 193-202, but is outside the loop starting on line 187. This may be a mistake such as bad indentation level causing the NameError shown above. If not a mistake, it may be best to move the code on those lines into a function, so it isn't repeated verbatim.

If these problems aren't reproducible, then maybe I have an issue with my BLAST setup?

**Comment by PB-Shinde** [comment]
Hello @schackartk, this issue is you need to mention the name of the blast file in command. For example: ALL_140821_hr.nhr is the name of your database files, then mention the name "ALL_140821_hr" in the end of the database path.

python3 MetaPhinder.py -i final.contigs.fa -o output -d /database/ALL_140821_hr -b /envs/metaphinder/bin/

I hope this helps.

**Comment by schackartk** [comment]
That was it, thank you. Maybe you could update the README to make this more clear?
